name: hello-world
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v4.1.1
      - run: echo "$(cat hello_world.txt)"
      # Second step ↓
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: '18.x'
      - run: npm install
      - run: npm run build
